const swaggerJsdoc = require('swagger-jsdoc');
const swaggerOptions = {
    // List of files to be processed.
    apis: ['./src/app/router/*.js'],
    // You can also set globs for your apis
    // e.g. './routes/*.js'
    basePath: '/',
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            title: 'Express Example API',
            contact: {
                name: "Thang Le"
            },
            servers: ["http://localhost:8585"],
        },
        schemes: ['http', 'https'],
        securityDefinitions: {
            Bearer: {
                type: 'apiKey',
                in: 'header',
                name: 'Authorization',
                description: "",
            }
        },
        security: [
            {
                Bearer: []
            }
        ]
    },
};

const swaggerDocs = swaggerJsdoc(swaggerOptions);
module.exports= swaggerDocs;